name: advent-of-code-haskell
version: 0.1.0.0
github: 'xenopol/advent-of-code-haskell'
license: BSD3
author: 'xenopol'
maintainer: 'example@example.com'
copyright: '2020 xenopol'

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/xenopol/advent-of-code-haskell#readme>

dependencies:
  - base >= 4.7 && < 5
  - tasty
  - tasty-hunit
  - split
  - pureMD5
  - bytestring

library:
  source-dirs:
    - src
